### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [kenomaerz/pymcws#4]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pymcws -w /tmp/ext pymcws==0.2.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pymcws==0.2.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/73e/4bbeb018bb504/pymcws-0.2.1.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-1v4ypiy4/pymcws/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-1v4ypiy4/pymcws/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-1v4ypiy4/pymcws/pip-egg-info
         cwd: /tmp/pip-wheel-1v4ypiy4/pymcws/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-1v4ypiy4/pymcws/setup.py", line 6, in <module>
        with open("history.md") as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'history.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kenomaerz** [comment]
Merged it. Much appreciated, Tim!
